const FIELD_LABEL_KEYS: Record<string, string> = {
  text: 'field_text',
  font: 'field_font',
  fontSize: 'field_font_size',
  fontWeight: 'field_font_weight',
  color: 'field_color',
  align: 'field_align',
  decoration: 'field_decoration',
  fontStyle: 'field_font_style',
  textDecoration: 'field_decoration',
  lineHeight: 'field_line_height',
  letter: 'field_letter',
  listStyle: 'field_list_style',
  transform: 'field_transform',
  width: 'field_width',
  height: 'field_height',
  minW: 'field_min_w',
  maxW: 'field_max_w',
  display: 'field_display',
  overflow: 'field_overflow',
  bgColor: 'field_bg_color',
  bgImage: 'field_bg_image',
  border: 'field_border',
  borderColor: 'field_border_color',
  radius: 'field_radius',
  shadow: 'field_shadow',
  shadowColor: 'field_shadow_color',
  opacity: 'field_opacity',
  blur: 'field_blur',
  margin: 'field_margin',
  padding: 'field_padding',
  fill: 'field_fill',
  stroke: 'field_stroke',
  strokeWidth: 'field_stroke_width',
  replaceImg: 'field_replace_img',
};

export function fieldLabelKey(prop: string): string | undefined {
  return FIELD_LABEL_KEYS[prop];
}
